language: objective-c
before_install:
  - brew update
  - brew install gfortran
  - brew tap homebrew/science
install:
  - mkdir -p $(brew --repo)/Library/Taps
  - ln -s $PWD $(brew --repo)/Library/Taps/travis-testtap
  - brew tap --repair
env:
  - PACKAGE=*
script:
  - brew audit $PACKAGE
  - brew install -v $PACKAGE
  - '! brew cat $PACKAGE | grep -q "test do" || brew test -v $PACKAGE'
